  bool handled_exception() const { return handled_exception_; }
